### ISSUE TITLE
modifiy readme.md where is the *.exe modbus TCP server...

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/electron-tf6250-server-test#2]
Hello @benhar-dev,
modify readme.md:
 where is the *.exe modbus TCP server?
Getting Started using installer
Download and run the TF6250 Server Tester Setup x.x.x.exe found in the releases.
- path => "C:\TwinCAT\Functions\TF6250-Modbus-TCP\Win32\Server"

![TF6250_ModbusTCP_Server](https://github.com/benhar-dev/electron-tf6250-server-test/assets/53791834/4192b359-4d2b-48d0-86a6-ad6cafae792a)

and how to configure?

- or download TF6250.Server.Tester.Setup.1.1.0.exe, assets...

**Comment by benhar-dev** [comment]
Hi @runtimevic, the readme has been updated 👍
