### ISSUE TITLE
Write to first coils: Modbus exception 2: illegal data address (register not supported by device)

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/electron-tf6250-server-test#3]
Hello @benhar-dev ,
Write to first coils: Modbus exception 2: illegal data address (register not supported by device)
I have this error, what am I doing wrong?

```javascript
async function WriteToFirstCoil(ipAddress) {
  const client = new ModbusRTU();
  await client.connectTCP(ipAddress, { port: MODBUS_PORT });
  await client.writeCoil(32768, true);
}
```

![TF6250_ModbusTCP_Server_Test_error](https://github.com/benhar-dev/electron-tf6250-server-test/assets/53791834/34cf1309-1ef6-433d-8c14-25b6ba48e12b)

**Comment by benhar-dev** [comment]
Hi @runtimevic, the readme has been updated 👍
