### ISSUE TITLE
project offline TwinCAT demo add license TF6250  TC3 Modbus-TCP

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/electron-tf6250-server-test#4]
Hello @benhar-dev,
The license TF6250  TC3 Modbus-TCP needs to be added to the project,
correct it...
with this and following the readme.md everything ok works correctly

**Comment by benhar-dev** [comment]
I'm pleased you have it working.  Just to confirm, this is step 5 of Windows 10, or step 6 of Windows CE.

**Comment by runtimevic** [comment]
> I'm pleased you have it working. Just to confirm, this is step 5 of Windows 10, or step 6 of Windows CE.

- step5 of windows 10
- The project does not have the license, if it is clicked by default better, then you don't have to worry about adding it...

**Comment by benhar-dev** [comment]
step 5 now has a picture 👍
